site_title = "MyArxiv"
limit_days = 7
cache_url = "https://jxncted.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 150
category = "cs.CV"
title = "Vision"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.SY"
title = "System/Control"

[[sources]]
limit = 150
category = "cs.OC"
title = "Optimization/Control"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
